stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: quantox/dev
  DOCKER_TAG: boi-site
  SERVICE_NAME: boi-site_stage

build-image:
  stage: build
  image: docker:dind
  services:
    - docker:dind
  tags:
    - docker
  environment:
    name: dev
    url: boi.qlab.quantox.dev
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  before_script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
  script:
    - docker build --tag "${DOCKER_IMAGE}":${DOCKER_TAG} --build-arg ENV_FILE="${ENV_FILE}" .
    - docker push "${DOCKER_IMAGE}":${DOCKER_TAG}

deploy:
  stage: deploy
  tags:
    - shell
  environment:
    name: dev
    url: boi.qlab.quantox.dev
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh ${DEV_SERVER_SSH} "docker service update --force --image "${DOCKER_IMAGE}":${DOCKER_TAG} --with-registry-auth ${SERVICE_NAME}"
