import Head from 'next/head'
import { useTranslations } from 'next-intl'

import { MainLayout } from '@/components/Layout'

import styles from '@/styles/Home.module.css'
import { Hero } from '@/components/Hero'
import { Testimonials } from '@/components/Testimonials'
import { Footer } from '@/components/Footer'

export default function Home() {
  const t = useTranslations('Home')

  return (
    <div className={styles.container}>
      <Head>
        <title>boi | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Hero />
      <Testimonials />
    </div>
  )
}

Home.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>
}

export async function getServerSideProps({ locale }) {
  return {
    props: {
      textContent: (await import(`../../locales/${locale}.json`)).default,
    },
  }
}
