import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>boi | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1 className="text-3xl font-bold">boi - homepage</h1>
    </div>
  )
}
